logging:
  level:
    org.springframework.core.env: DEBUG
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3308/demo?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: demo
    password: demo
  jpa:
    show-sql: true
  config:
    import: optional:file:.env.properties
  jwt:
    secret: ${JWT_SECRET}
server:
  port: 9091





